
name: Maven CI/CD

on:
 push:
    branches: 
     - dev
 pull_request:
    branches: 
     - dev

jobs:
  build:
    name: Build on JDK ${{ matrix.java }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [8, 11]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8.0_251
      uses: actions/setup-java@v1
      with:
        java-version: 1.8.0_251

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
